// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wukuntxccrgvtpiifaut.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind1a3VudHhjY3JndnRwaWlmYXV0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc4MTM1MzMsImV4cCI6MjA2MzM4OTUzM30.vOui6ZKkqnyvwuq_ohCAImLlvjUE3a84bKpBTcx_zDY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);